apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightshift
spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nightshift
              image: sandbox-nightshift
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
      backoffLimit: 4
      activeDeadlineSeconds: 600
